<?php
$apikey ="rzp_test_hCOztGoq8AEJp2";
?>
<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount']*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID' .rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
   
    data-name="Sachins Forum"
    data-description="Training and development"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="<?php echo $_POST['Fname'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.mobile="<?php echo $_POST['mobile'];?>"
    data-theme.color="black"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>